Assignment   react implementation
Louisdrejer/stackoverflow_v2.0 pull request #3
Opened 2023-11-08 09:36 UTC by Louisdrejer

assignment 08-11-2023

2023-11-09 15:41 UTC, igawaclawska commented on src/App.css
> +.submitButton{
Consider naming CSS selectors using kebab-case.
https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

2023-11-09 16:10 UTC, igawaclawska commented on src/Components/LeftNav.jsx
> +        <img src={logo} alt="Logo" style={{ maxWidth: "70%", marginLeft: "15%" }} />
Please avoid inline styling.

2023-11-09 16:19 UTC, igawaclawska commented on src/Pages/Login/Login2.jsx
> +import "./Login2.css"
Why does Login have two separate files? Login.jsx and Login2.jsx ?

2023-11-09 16:55 UTC, igawaclawska commented on src/img/something.js
> +
What's this?

2023-11-09 16:57 UTC, igawaclawska commented on src/Pages/SearchPage/SearchPage.jsx
> +
Good job on naming these handlers!

2023-11-09 17:07 UTC, igawaclawska commented on src/App.jsx
> +function App() {
I see 2 App files (App.js and App.jsx). 
Are both of them needed? If not - consider removing the redundant one.

2023-11-09 17:27 UTC, igawaclawska commented on src/Pages/Answerpage/Answerpage.jsx
> +export default function Homepage() {
Answerpage.jsx looks identical to Homepage.jsx
What about using just one of them?

2023-11-09 18:03 UTC, igawaclawska commented on src/Pages/Login/Login2.css
> +/*.mainContainerLogin2 {
If a file or commented-out code is no longer needed, consider removing it.

2023-11-09 18:25 UTC, igawaclawska requested changes
Overall looks good, but please take a look at the comments and try to implement changes. Ping us once you're done. :)

2023-11-23 14:43 UTC, merged

2023-11-29 13:34 UTC, mircealungu commented
Hey people, we see that this is merged, while the state of the branch is **changes requested**. You have to make it clear that you have addressed the changes before merging. Either individually answering the comments, or adding a single final comment saying that you've handled everything. So, what happened here?